# Generated by Django 4.2.4 on 2023-08-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_verification', '0002_remove_customuser_is_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
