# Generated by Django 4.2.4 on 2023-08-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_verification', '0004_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(max_length=6, unique=True)),
            ],
        ),
    ]
