# Generated by Django 4.2.4 on 2023-08-19 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_verification', '0005_invitecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friend_invite_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friend_invite', to='user_verification.invitecode'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='my_invite_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_invite', to='user_verification.invitecode'),
        ),
    ]
